/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare const CartesiaEnvironment: {
    readonly Default: "https://api.plantstore.dev/v3";
};
export type CartesiaEnvironment = typeof CartesiaEnvironment.Default;
