/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Cartesia from "../../api/index";
import * as core from "../../core";
export declare const PlantStatus: core.serialization.Schema<serializers.PlantStatus.Raw, Cartesia.PlantStatus>;
export declare namespace PlantStatus {
    type Raw = "available" | "pending" | "sold";
}
