/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Cartesia from "../../api/index";
import * as core from "../../core";
export declare const UserAuthResponse: core.serialization.ObjectSchema<serializers.UserAuthResponse.Raw, Cartesia.UserAuthResponse>;
export declare namespace UserAuthResponse {
    interface Raw {
        token?: string | null;
        expiresIn?: number | null;
    }
}
