/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Cartesia from "../index";
export interface Plant {
    name?: string;
    category?: string;
    tags?: string[];
    status?: Cartesia.PlantStatus;
}
