/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.plant.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import resources.plant.types.SearchPlantsByStatusRequestStatus;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = SearchPlantsByStatusRequest.Builder.class
)
public final class SearchPlantsByStatusRequest {
  private final Optional<SearchPlantsByStatusRequestStatus> status;

  private final Map<String, Object> additionalProperties;

  private SearchPlantsByStatusRequest(Optional<SearchPlantsByStatusRequestStatus> status,
      Map<String, Object> additionalProperties) {
    this.status = status;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The status of plants to search for.
   */
  @JsonProperty("status")
  public Optional<SearchPlantsByStatusRequestStatus> getStatus() {
    return status;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof SearchPlantsByStatusRequest && equalTo((SearchPlantsByStatusRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(SearchPlantsByStatusRequest other) {
    return status.equals(other.status);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.status);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<SearchPlantsByStatusRequestStatus> status = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(SearchPlantsByStatusRequest other) {
      status(other.getStatus());
      return this;
    }

    @JsonSetter(
        value = "status",
        nulls = Nulls.SKIP
    )
    public Builder status(Optional<SearchPlantsByStatusRequestStatus> status) {
      this.status = status;
      return this;
    }

    public Builder status(SearchPlantsByStatusRequestStatus status) {
      this.status = Optional.ofNullable(status);
      return this;
    }

    public SearchPlantsByStatusRequest build() {
      return new SearchPlantsByStatusRequest(status, additionalProperties);
    }
  }
}
