// This file was auto-generated by Fern from our API Definition.

package client

import (
	http "net/http"
	core "sdk/core"
	internal "sdk/internal"
	option "sdk/option"
	plant "sdk/plant"
	user "sdk/user"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header

	Plant *plant.Client
	User  *user.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
		Plant:  plant.NewClient(opts...),
		User:   user.NewClient(opts...),
	}
}
