# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing_extensions
import typing
from ..types.plant_status import PlantStatus


class PlantParams(typing_extensions.TypedDict):
    name: typing_extensions.NotRequired[str]
    category: typing_extensions.NotRequired[str]
    tags: typing_extensions.NotRequired[typing.Sequence[str]]
    status: typing_extensions.NotRequired[PlantStatus]
