# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing_extensions


class UserParams(typing_extensions.TypedDict):
    id: typing_extensions.NotRequired[int]
    username: typing_extensions.NotRequired[str]
    email: typing_extensions.NotRequired[str]
