/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PlantResponse.Builder.class
)
public final class PlantResponse {
  private final Optional<Integer> id;

  private final Optional<String> name;

  private final Optional<String> status;

  private final Optional<List<String>> tags;

  private final Map<String, Object> additionalProperties;

  private PlantResponse(Optional<Integer> id, Optional<String> name, Optional<String> status,
      Optional<List<String>> tags, Map<String, Object> additionalProperties) {
    this.id = id;
    this.name = name;
    this.status = status;
    this.tags = tags;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("id")
  public Optional<Integer> getId() {
    return id;
  }

  @JsonProperty("name")
  public Optional<String> getName() {
    return name;
  }

  @JsonProperty("status")
  public Optional<String> getStatus() {
    return status;
  }

  @JsonProperty("tags")
  public Optional<List<String>> getTags() {
    return tags;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PlantResponse && equalTo((PlantResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PlantResponse other) {
    return id.equals(other.id) && name.equals(other.name) && status.equals(other.status) && tags.equals(other.tags);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.name, this.status, this.tags);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Integer> id = Optional.empty();

    private Optional<String> name = Optional.empty();

    private Optional<String> status = Optional.empty();

    private Optional<List<String>> tags = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(PlantResponse other) {
      id(other.getId());
      name(other.getName());
      status(other.getStatus());
      tags(other.getTags());
      return this;
    }

    @JsonSetter(
        value = "id",
        nulls = Nulls.SKIP
    )
    public Builder id(Optional<Integer> id) {
      this.id = id;
      return this;
    }

    public Builder id(Integer id) {
      this.id = Optional.ofNullable(id);
      return this;
    }

    @JsonSetter(
        value = "name",
        nulls = Nulls.SKIP
    )
    public Builder name(Optional<String> name) {
      this.name = name;
      return this;
    }

    public Builder name(String name) {
      this.name = Optional.ofNullable(name);
      return this;
    }

    @JsonSetter(
        value = "status",
        nulls = Nulls.SKIP
    )
    public Builder status(Optional<String> status) {
      this.status = status;
      return this;
    }

    public Builder status(String status) {
      this.status = Optional.ofNullable(status);
      return this;
    }

    @JsonSetter(
        value = "tags",
        nulls = Nulls.SKIP
    )
    public Builder tags(Optional<List<String>> tags) {
      this.tags = tags;
      return this;
    }

    public Builder tags(List<String> tags) {
      this.tags = Optional.ofNullable(tags);
      return this;
    }

    public PlantResponse build() {
      return new PlantResponse(id, name, status, tags, additionalProperties);
    }
  }
}
