/**
 * This file was auto-generated by Fern from our API Definition.
 */

package errors;

import core.PlantstoreApiApiException;
import java.lang.Object;

public final class BadRequestError extends PlantstoreApiApiException {
  /**
   * The body of the response that triggered the exception.
   */
  private final Object body;

  public BadRequestError(Object body) {
    super("BadRequestError", 400, body);
    this.body = body;
  }

  /**
   * @return the body
   */
  @java.lang.Override
  public Object body() {
    return this.body;
  }
}
