/**
 * This file was auto-generated by Fern from our API Definition.
 */

import core.ClientOptions;
import core.Environment;
import java.lang.String;
import okhttp3.OkHttpClient;

public final class PlantstoreApiClientBuilder {
  private ClientOptions.Builder clientOptionsBuilder = ClientOptions.builder();

  private Environment environment = Environment.DEFAULT;

  public PlantstoreApiClientBuilder environment(Environment environment) {
    this.environment = environment;
    return this;
  }

  public PlantstoreApiClientBuilder url(String url) {
    this.environment = Environment.custom(url);
    return this;
  }

  /**
   * Sets the timeout (in seconds) for the client
   */
  public PlantstoreApiClientBuilder timeout(int timeout) {
    this.clientOptionsBuilder.timeout(timeout);
    return this;
  }

  /**
   * Sets the underlying OkHttp client
   */
  public PlantstoreApiClientBuilder httpClient(OkHttpClient httpClient) {
    this.clientOptionsBuilder.httpClient(httpClient);
    return this;
  }

  public PlantstoreApiClient build() {
    clientOptionsBuilder.environment(this.environment);
    return new PlantstoreApiClient(clientOptionsBuilder.build());
  }
}
