/**
 * This file was auto-generated by Fern from our API Definition.
 */

import core.ClientOptions;
import core.Suppliers;
import java.util.function.Supplier;
import resources.plant.PlantClient;
import resources.user.UserClient;

public class PlantstoreApiClient {
  protected final ClientOptions clientOptions;

  protected final Supplier<PlantClient> plantClient;

  protected final Supplier<UserClient> userClient;

  public PlantstoreApiClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.plantClient = Suppliers.memoize(() -> new PlantClient(clientOptions));
    this.userClient = Suppliers.memoize(() -> new UserClient(clientOptions));
  }

  public PlantClient plant() {
    return this.plantClient.get();
  }

  public UserClient user() {
    return this.userClient.get();
  }

  public static PlantstoreApiClientBuilder builder() {
    return new PlantstoreApiClientBuilder();
  }
}
